// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqB67A-yQ1jOz8M63pilPWffdeU0OqBUw',
    appId: '1:1001580312107:web:9fbfbefc30b4d4f1129c6e',
    messagingSenderId: '1001580312107',
    projectId: 'minimal-3b0fd',
    authDomain: 'minimal-3b0fd.firebaseapp.com',
    storageBucket: 'minimal-3b0fd.appspot.com',
    measurementId: 'G-2BCTS2L2TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8peTOD9LtC--2Znwd0S5O-XXRuuxfOU',
    appId: '1:1001580312107:android:b127374536c5344c129c6e',
    messagingSenderId: '1001580312107',
    projectId: 'minimal-3b0fd',
    storageBucket: 'minimal-3b0fd.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqB67A-yQ1jOz8M63pilPWffdeU0OqBUw',
    appId: '1:1001580312107:web:683dfcefe57ae672129c6e',
    messagingSenderId: '1001580312107',
    projectId: 'minimal-3b0fd',
    authDomain: 'minimal-3b0fd.firebaseapp.com',
    storageBucket: 'minimal-3b0fd.appspot.com',
    measurementId: 'G-R4H7SR53S6',
  );
}
